### ISSUE TITLE
Partition Key not portable across environments

### ISSUE THREAD

**Issue by gplwhite** [serilog-contrib/serilog-sinks-azuretablestorage#35]
Currently the DefaultKeyGenerator uses Timestamp.UtcDateTime.Ticks as the partition key. 

However, using the Ticks property of DateTimeOffset returns the number of ticks based on the current time (including timezone offset).

The problem here is that events logged by different hosts at exactly the same instant but where the hosts have different timezone settings, will be recorded with different partition keys.  

I think the DefaultKeyGenerator should actually be using the UtcTicks property. This would give a consistent partition key regardless of host machine settings.

**Comment by adriannasui** [comment]
I think ticks is useless because it does not allow for easy searching. 
When the table gets big, you need a partition key that you can filter by in searches. 
I am thinking of implementing a custom key generator where the partition is of the fomat "yyyyMMdd" such that I can easily use it in a search to get faster results. 
A bit of details about the Azure Table Storage partitions on the [Microsoft site here](https://docs.microsoft.com/en-us/rest/api/storageservices/designing-a-scalable-partitioning-strategy-for-azure-table-storage).

**Comment by pwelter34** [comment]
The new DefaultKeyGenerator uses a rounded timespan to partition logs in 5 min buckets.   Time based partition key performance issue is mediated by batch writing by default.
